/*
 * @(#) CapiHumano.java
 * 
 * Copyright (c) Software Solutions
 * Todos los derechos reservados
 * 
 */
package si;

import java.util.Vector;

/**
 * @version 1.0 02/12/12
 * 
 * @author Ricardo Rangel Rangel
 */

public class CapiHumano extends javax.swing.JFrame {
    private String nombre;
    private String paterno;
    private String materno;
    private String cedula;
    private String turno;
    private int telefono;
    private String departamento;
    private String calle;
    private int numero;
    private String colonia;
    private int año;
    private int mes;
    private int dia;
    private String rfc;
    private String materias;
    private double sueldo;
    private String afiliacion;
    private int edad;
    private String empleo;
    
    
    /**
     * Creates new form CapiHumano
     */
    public CapiHumano() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2TodosLosDatosEmpleados = new javax.swing.JTextArea();
        jButton1DatosEmpleadosMatutino = new javax.swing.JButton();
        jButton2DatosEmpleadosVespertino = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1LimpiarConsulta = new javax.swing.JButton();
        ButtonConsultar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1DatosEmpleado = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea3NombresEmpleados = new javax.swing.JTextArea();
        jTextField1ConsultaEmpleados = new javax.swing.JTextField();
        jButton3BuscarEmpleado = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton4NoombresEmpleadosMatutino = new javax.swing.JButton();
        jButton5NombresEmpleadosVespertino = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextField2Buscar = new javax.swing.JTextField();
        jButton6BuscarDatosTrabajador = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField3Nombre = new javax.swing.JTextField();
        jTextField4Paterno = new javax.swing.JTextField();
        jTextField5Cedula = new javax.swing.JTextField();
        jTextField6Telefono = new javax.swing.JTextField();
        jTextField7Calle = new javax.swing.JTextField();
        jTextField8Rfc = new javax.swing.JTextField();
        jTextField9Materias = new javax.swing.JTextField();
        jTextField10Sueldo = new javax.swing.JTextField();
        jTextField11Edad = new javax.swing.JTextField();
        jTextField12Empleo = new javax.swing.JTextField();
        jTextField13Materno = new javax.swing.JTextField();
        jTextField14Turno = new javax.swing.JTextField();
        jTextField15Departamento = new javax.swing.JTextField();
        jTextField16Colonia = new javax.swing.JTextField();
        jTextField17Afiliacion = new javax.swing.JTextField();
        jButton8CancelarModificaciónEmpleado = new javax.swing.JButton();
        jTextField1Numero = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextField18Año = new javax.swing.JTextField();
        jTextField19Mes = new javax.swing.JTextField();
        jTextField20Dia = new javax.swing.JTextField();
        jButton1GuardarInformacion = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jTextField18BajaConAfiliacion = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField19bajaConcedula = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jButton9BajaConAfiliacion = new javax.swing.JButton();
        jButton10BajaConCedula = new javax.swing.JButton();
        jButton11CancelarBaja = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextArea2TodosLosDatosEmpleados.setColumns(20);
        jTextArea2TodosLosDatosEmpleados.setRows(5);
        jScrollPane3.setViewportView(jTextArea2TodosLosDatosEmpleados);

        jScrollPane4.setViewportView(jScrollPane3);

        jButton1DatosEmpleadosMatutino.setText("Matutino");
        jButton1DatosEmpleadosMatutino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1DatosEmpleadosMatutinoMouseClicked(evt);
            }
        });

        jButton2DatosEmpleadosVespertino.setText("Vespertino");
        jButton2DatosEmpleadosVespertino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2DatosEmpleadosVespertinoMouseClicked(evt);
            }
        });

        jLabel4.setText("Datos de todos los empleados");

        jButton1LimpiarConsulta.setText("Limpiar");
        jButton1LimpiarConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1LimpiarConsultaMouseClicked(evt);
            }
        });

        ButtonConsultar.setText("Consultar");
        ButtonConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonConsultarMouseClicked(evt);
            }
        });
        ButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jButton1DatosEmpleadosMatutino)
                        .addGap(89, 89, 89)
                        .addComponent(jButton1LimpiarConsulta)
                        .addGap(77, 77, 77)
                        .addComponent(jButton2DatosEmpleadosVespertino)
                        .addGap(48, 48, 48)
                        .addComponent(ButtonConsultar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1DatosEmpleadosMatutino)
                    .addComponent(jButton2DatosEmpleadosVespertino)
                    .addComponent(jButton1LimpiarConsulta)
                    .addComponent(ButtonConsultar))
                .addContainerGap(178, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consulta (todos los empleados)", jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextArea1DatosEmpleado.setColumns(20);
        jTextArea1DatosEmpleado.setRows(5);
        jScrollPane1.setViewportView(jTextArea1DatosEmpleado);

        jScrollPane2.setViewportView(jScrollPane1);

        jTextArea3NombresEmpleados.setColumns(20);
        jTextArea3NombresEmpleados.setRows(5);
        jScrollPane5.setViewportView(jTextArea3NombresEmpleados);

        jScrollPane6.setViewportView(jScrollPane5);

        jButton3BuscarEmpleado.setText("Buscar");
        jButton3BuscarEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3BuscarEmpleadoMouseClicked(evt);
            }
        });

        jLabel1.setText("introduzca el nombre completo:");

        jLabel2.setText("Datos del empleado:");

        jLabel3.setText("Nombres de todos los empleados");

        jButton4NoombresEmpleadosMatutino.setText("Matutino");
        jButton4NoombresEmpleadosMatutino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4NoombresEmpleadosMatutinoMouseClicked(evt);
            }
        });

        jButton5NombresEmpleadosVespertino.setText("Vespertino");
        jButton5NombresEmpleadosVespertino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5NombresEmpleadosVespertinoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextField1ConsultaEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3BuscarEmpleado))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(95, 95, 95)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton4NoombresEmpleadosMatutino)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5NombresEmpleadosVespertino)))))
                .addContainerGap(256, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1ConsultaEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3BuscarEmpleado))
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4NoombresEmpleadosMatutino)
                    .addComponent(jButton5NombresEmpleadosVespertino))
                .addContainerGap(185, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consulta (empleado específico)", jPanel3);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton6BuscarDatosTrabajador.setText("Buscar");
        jButton6BuscarDatosTrabajador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6BuscarDatosTrabajadorMouseClicked(evt);
            }
        });

        jLabel5.setText("Escriba el nombre el del trabajador:");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel6.setText("Nombre:");

        jLabel7.setText("Apellido paterno:");

        jLabel8.setText("Apellido materno:");

        jLabel9.setText("Cédula profesional:");

        jLabel10.setText("Turno:");

        jLabel11.setText("Teléfono:");

        jLabel12.setText("Departamento:");

        jLabel13.setText("Calle:");

        jLabel14.setText("#");

        jLabel15.setText("Colonia:");

        jLabel16.setText("RFC:");

        jLabel17.setText("Materias::");

        jLabel18.setText("Sueldo:");

        jLabel19.setText("Afiliación al IMSS o al ISSSTE:");

        jLabel20.setText("Edad:");

        jLabel21.setText("Empleo:");

        jLabel22.setText("Algunos campos no son obligatorios");

        jTextField5Cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5CedulaActionPerformed(evt);
            }
        });

        jTextField6Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6TelefonoActionPerformed(evt);
            }
        });

        jTextField7Calle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7CalleActionPerformed(evt);
            }
        });

        jTextField12Empleo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12EmpleoActionPerformed(evt);
            }
        });

        jTextField14Turno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14TurnoActionPerformed(evt);
            }
        });

        jTextField15Departamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15DepartamentoActionPerformed(evt);
            }
        });

        jTextField16Colonia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ColoniaActionPerformed(evt);
            }
        });

        jButton8CancelarModificaciónEmpleado.setText("Cancelar");
        jButton8CancelarModificaciónEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8CancelarModificaciónEmpleadoMouseClicked(evt);
            }
        });

        jLabel26.setText("Fecha de contratación:");

        jLabel27.setText("Día:");

        jLabel28.setText("Mes:");

        jLabel29.setText("Año:");

        jTextField19Mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField19MesActionPerformed(evt);
            }
        });

        jButton1GuardarInformacion.setText("Guardar");
        jButton1GuardarInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1GuardarInformacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel22))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField3Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                    .addComponent(jTextField4Paterno)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21))
                                .addGap(7, 7, 7)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField6Telefono, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField5Cedula)
                                    .addComponent(jTextField7Calle)
                                    .addComponent(jTextField8Rfc)
                                    .addComponent(jTextField10Sueldo)
                                    .addComponent(jTextField11Edad)
                                    .addComponent(jTextField12Empleo)
                                    .addComponent(jTextField9Materias))))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField1Numero, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(jTextField19Mes, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel10))
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jTextField13Materno, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                    .addGap(7, 7, 7)
                                                    .addComponent(jTextField14Turno, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel12)
                                                .addComponent(jLabel15)
                                                .addComponent(jLabel27))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextField15Departamento)
                                                .addComponent(jTextField16Colonia)
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                    .addComponent(jTextField20Dia, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(0, 0, Short.MAX_VALUE)))))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton1GuardarInformacion)
                                            .addComponent(jTextField17Afiliacion, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(241, 241, 241)
                                .addComponent(jButton8CancelarModificaciónEmpleado))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField18Año, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField3Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jTextField4Paterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField13Materno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jTextField5Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField14Turno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jTextField6Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField15Departamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jTextField7Calle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField16Colonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(jTextField18Año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField19Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField20Dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField8Rfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextField9Materias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jTextField10Sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField17Afiliacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextField11Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1GuardarInformacion))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jTextField12Empleo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(jLabel22)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jButton8CancelarModificaciónEmpleado)))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField2Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton6BuscarDatosTrabajador))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6BuscarDatosTrabajador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Modificar", jPanel1);

        jTextField18BajaConAfiliacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18BajaConAfiliacionActionPerformed(evt);
            }
        });

        jLabel23.setText("Introduzca el número de afiliación al IMSS o al ISSSTE:");

        jLabel24.setText("Ó");

        jTextField19bajaConcedula.setText("jTextField19BajaConCedula");
        jTextField19bajaConcedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField19bajaConcedulaActionPerformed(evt);
            }
        });

        jLabel25.setText("Escriba la clave de la cédula profesional:");

        jButton9BajaConAfiliacion.setText("Baja");
        jButton9BajaConAfiliacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9BajaConAfiliacionMouseClicked(evt);
            }
        });
        jButton9BajaConAfiliacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9BajaConAfiliacionActionPerformed(evt);
            }
        });

        jButton10BajaConCedula.setText("Baja");
        jButton10BajaConCedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10BajaConCedulaMouseClicked(evt);
            }
        });

        jButton11CancelarBaja.setText("Cancelar");
        jButton11CancelarBaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11CancelarBajaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel24))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField18BajaConAfiliacion))
                                .addGap(18, 18, 18)
                                .addComponent(jButton9BajaConAfiliacion))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField19bajaConcedula, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jButton10BajaConCedula)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 468, Short.MAX_VALUE)
                .addComponent(jButton11CancelarBaja)
                .addGap(387, 387, 387))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField18BajaConAfiliacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9BajaConAfiliacion))
                .addGap(42, 42, 42)
                .addComponent(jLabel24)
                .addGap(28, 28, 28)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField19bajaConcedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10BajaConCedula))
                .addGap(109, 109, 109)
                .addComponent(jButton11CancelarBaja)
                .addContainerGap(231, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dar de baja", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2DatosEmpleadosVespertinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2DatosEmpleadosVespertinoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2DatosEmpleadosVespertinoMouseClicked

    private void jButton1DatosEmpleadosMatutinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1DatosEmpleadosMatutinoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1DatosEmpleadosMatutinoMouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jTextField14TurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14TurnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14TurnoActionPerformed

    private void jButton8CancelarModificaciónEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8CancelarModificaciónEmpleadoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8CancelarModificaciónEmpleadoMouseClicked

    private void jTextField19bajaConcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19bajaConcedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19bajaConcedulaActionPerformed

    private void jButton9BajaConAfiliacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9BajaConAfiliacionActionPerformed
        // TODO add your handling code here:
        
        String afiliacionBusqueda = jTextField18BajaConAfiliacion.getText();
        BajaDeTrabajador bajaDeTrabajador = new BajaDeTrabajador(afiliacionBusqueda);
    }//GEN-LAST:event_jButton9BajaConAfiliacionActionPerformed

    private void jButton6BuscarDatosTrabajadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6BuscarDatosTrabajadorMouseClicked
        // TODO add your handling code here:
   
    }//GEN-LAST:event_jButton6BuscarDatosTrabajadorMouseClicked

    private void jButton9BajaConAfiliacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9BajaConAfiliacionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9BajaConAfiliacionMouseClicked

    private void jButton10BajaConCedulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10BajaConCedulaMouseClicked
        // TODO add your handling code here:
        
        
        String cedulaBusqueda = jTextField19bajaConcedula.getText();
        BajaDeTrabajadorC bajaDeTrabajadorC = new BajaDeTrabajadorC(cedulaBusqueda);
    }//GEN-LAST:event_jButton10BajaConCedulaMouseClicked

    private void jButton11CancelarBajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11CancelarBajaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11CancelarBajaMouseClicked

    private void jButton3BuscarEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3BuscarEmpleadoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3BuscarEmpleadoMouseClicked

    private void jButton4NoombresEmpleadosMatutinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4NoombresEmpleadosMatutinoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4NoombresEmpleadosMatutinoMouseClicked

    private void jButton5NombresEmpleadosVespertinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5NombresEmpleadosVespertinoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5NombresEmpleadosVespertinoMouseClicked

    private void jTextField5CedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5CedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5CedulaActionPerformed

    private void jTextField7CalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7CalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7CalleActionPerformed

    private void jTextField15DepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15DepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15DepartamentoActionPerformed

    private void jTextField16ColoniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ColoniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ColoniaActionPerformed

    private void jTextField6TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6TelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6TelefonoActionPerformed

    private void jTextField19MesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19MesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19MesActionPerformed

    private void jTextField12EmpleoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12EmpleoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12EmpleoActionPerformed

    private void jTextField18BajaConAfiliacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18BajaConAfiliacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18BajaConAfiliacionActionPerformed

    private void jButton1LimpiarConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1LimpiarConsultaMouseClicked
        // TODO add your handling code here:
        
        
        jTextArea2TodosLosDatosEmpleados.setText("");
    }//GEN-LAST:event_jButton1LimpiarConsultaMouseClicked

    private void ButtonConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonConsultarMouseClicked
        // TODO add your handling code here:
        
        
        ConsultaTrabajador consultaTrabajadorNum = new ConsultaTrabajador();
        Vector<Empleados> personalNuevoCon = consultaTrabajadorNum.getPersonalNuevo();
        
        for (Empleados e : personalNuevoCon){
            jTextArea2TodosLosDatosEmpleados.append("Empleado: " + e + "\n");
        }
    }//GEN-LAST:event_ButtonConsultarMouseClicked

    private void ButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonConsultarActionPerformed

    private void jButton1GuardarInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1GuardarInformacionActionPerformed
        // TODO add your handling code here:
        
        
        nombre = jTextField3Nombre.getText();
        paterno = jTextField4Paterno.getText();
        materno = jTextField13Materno.getText();
        rfc = jTextField8Rfc.getText();
        edad = Integer.parseInt(jTextField11Edad.getText());
        calle = jTextField7Calle.getText();
        numero = Integer.parseInt(jTextField1Numero.getText());
        colonia = jTextField16Colonia.getText();
        telefono = Integer.parseInt(jTextField6Telefono.getText());
        afiliacion = jTextField17Afiliacion.getText();
        sueldo = Double.parseDouble(jTextField10Sueldo.getText());
        año = Integer.parseInt(jTextField18Año.getText());
        mes = Integer.parseInt(jTextField19Mes.getText());
        dia = Integer.parseInt(jTextField20Dia.getText());
        cedula = jTextField5Cedula.getText();
        empleo = jTextField12Empleo.getText();
        turno = jTextField14Turno.getText();
        departamento = jTextField15Departamento.getText();
        materias = jTextField9Materias.getText();
        
        
        Empleados nuevoTrabajador;
        nuevoTrabajador = new Empleados (nombre, paterno, materno, 
  rfc, edad, calle, numero, colonia, telefono, 
  afiliacion, sueldo, año, mes, dia,
  cedula, empleo, turno, departamento, materias);
        AltaTrabajador altaTrabajador = new AltaTrabajador(nuevoTrabajador);
        
   
        jTextField3Nombre.setText("");
        jTextField4Paterno.setText("");
        jTextField13Materno.setText("");
        jTextField5Cedula.setText("");
        jTextField14Turno.setText("");
        jTextField6Telefono.setText("");
        jTextField16Colonia.setText("");
        jTextField20Dia.setText("");
        jTextField19Mes.setText("");
        jTextField18Año.setText("");
        jTextField9Materias.setText("");
        jTextField10Sueldo.setText("");
        jTextField17Afiliacion.setText("");
        jTextField11Edad.setText("");
        jTextField12Empleo.setText("");
        jTextField8Rfc.setText("");
        jTextField7Calle.setText("");
        jTextField1Numero.setText("");
        jTextField15Departamento.setText("");
      
                
    }//GEN-LAST:event_jButton1GuardarInformacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CapiHumano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CapiHumano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CapiHumano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CapiHumano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CapiHumano().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonConsultar;
    private javax.swing.JButton jButton10BajaConCedula;
    private javax.swing.JButton jButton11CancelarBaja;
    private javax.swing.JButton jButton1DatosEmpleadosMatutino;
    private javax.swing.JButton jButton1GuardarInformacion;
    private javax.swing.JButton jButton1LimpiarConsulta;
    private javax.swing.JButton jButton2DatosEmpleadosVespertino;
    private javax.swing.JButton jButton3BuscarEmpleado;
    private javax.swing.JButton jButton4NoombresEmpleadosMatutino;
    private javax.swing.JButton jButton5NombresEmpleadosVespertino;
    private javax.swing.JButton jButton6BuscarDatosTrabajador;
    private javax.swing.JButton jButton8CancelarModificaciónEmpleado;
    private javax.swing.JButton jButton9BajaConAfiliacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1DatosEmpleado;
    private javax.swing.JTextArea jTextArea2TodosLosDatosEmpleados;
    private javax.swing.JTextArea jTextArea3NombresEmpleados;
    private javax.swing.JTextField jTextField10Sueldo;
    private javax.swing.JTextField jTextField11Edad;
    private javax.swing.JTextField jTextField12Empleo;
    private javax.swing.JTextField jTextField13Materno;
    private javax.swing.JTextField jTextField14Turno;
    private javax.swing.JTextField jTextField15Departamento;
    private javax.swing.JTextField jTextField16Colonia;
    private javax.swing.JTextField jTextField17Afiliacion;
    private javax.swing.JTextField jTextField18Año;
    private javax.swing.JTextField jTextField18BajaConAfiliacion;
    private javax.swing.JTextField jTextField19Mes;
    private javax.swing.JTextField jTextField19bajaConcedula;
    private javax.swing.JTextField jTextField1ConsultaEmpleados;
    private javax.swing.JTextField jTextField1Numero;
    private javax.swing.JTextField jTextField20Dia;
    private javax.swing.JTextField jTextField2Buscar;
    private javax.swing.JTextField jTextField3Nombre;
    private javax.swing.JTextField jTextField4Paterno;
    private javax.swing.JTextField jTextField5Cedula;
    private javax.swing.JTextField jTextField6Telefono;
    private javax.swing.JTextField jTextField7Calle;
    private javax.swing.JTextField jTextField8Rfc;
    private javax.swing.JTextField jTextField9Materias;
    // End of variables declaration//GEN-END:variables
}
